### ISSUE TITLE
socket close error

### ISSUE THREAD

**Issue by zhezhe168** [7054company/plesk-unlimited-license#1]
[root@ /]# 7ea ea7plesk
The gates of heaven remain closed
Connection closing...Socket close.

Connection closed by foreign host.

**Comment by 7054company** [comment]
What you system os please re  download the 7ea ubuntu from url

**Comment by 7054company** [comment]
Please give me also details about your os??

**Comment by 7054company** [comment]
Ok wait wait , that not a problem
1. What is your os type??
2. please download correct binary , if ubuntu then ubuntu , if centos then centos 
3. Ubuntu is fully working 
4. centos is in tested period fix in 4h 
5. If your download binary not work in your system give me a temporay acces to your system using tmate ( i will install 7ea for you)
6. Thanks for raising issue

**Comment by 7054company** [comment]
Now issue is fixed run on any linux os , will work 
Thanks for reporting

**Comment by zhezhe168** [comment]
> Now issue is fixed run on any linux os , will work Thanks for reporting

okay,it works,by the ways,is it permanent?

**Comment by zhezhe168** [comment]
> Now issue is fixed run on any linux os , will work Thanks for reporting

new problem,I have to run in command with:
/bin/7ea ea7plesk
otherwise it shows:
7ea: 7ea: No such file or directory 
when run in command with:7ea ea7plesk

**Comment by 7054company** [comment]
Ya thanks , when you report the issue about the script not work so we rebuild the script and increase more security 
So it cause 
you can not directly 7ea from any where 
You have to run like
1. /bin/7ea
2. /usr/bin/7ea
3. 7ea script current directory then ./7ea
Soon , we will fix it 
We are live , 24*7 any problem just fire issue or email any time anyway!
Thanks for you

**Comment by 7054company** [comment]
Please send a screenshot if you can??

**Comment by 7054company** [comment]
You can try one more feature 
/bin/7ea ip           =>   It gives your ip
/bin/7ea ea7plesk  =>  to setup plesk
/bin/7ea 

But remember fire any unkown command 
It break you many lib because it is in development state as you know

**Comment by 7054company** [comment]
No it is permanent free license to your server it say to run the command to fix all the background issue and to update all changes made by us in ea7plesk to make more stable ..
It is at zero cost , you can fire it unlimted time no restriction Unless we do it..

**Comment by zhezhe168** [comment]
> > 
> 
> ya , it is permanant free license to your server And require to run in a week (as you wish time) it say to run the command to fix all the background issue and to maintain the new license and to update all changes made by us in ea7plesk to make more stable .. It is at zero cost , you can fire it unlimted time no restriction Unless we do it..

ok,thx,I will try it
